/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FsmBuilder: typeof import('./src/components/FsmBuilder.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
