packages: []

catalogs:
  build:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/mdi': ^1.2.3
    '@vitejs/plugin-vue': ^6.0.1
    peggy: ^5.0.6
    unocss: ^66.5.2
    unplugin: ^2.3.10
    unplugin-auto-import: ^20.2.0
    unplugin-vue-components: ^29.1.0
    unplugin-vue-macros: ^2.14.5
    vite: ^6.3.6
    vite-plugin-peggy-loader: ^2.0.1
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@types/node': ^22.18.6
    '@types/toastify-js': ^1.12.4
    '@unocss/eslint-plugin': ^66.5.2
    '@vue-macros/volar': ^3.1.0
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    typescript: ^5.9.2
    vue-tsc: ^3.0.8
  frontend:
    '@vueuse/core': ^13.9.0
    lz-string: ^1.5.0
    toastify-js: ^1.12.0
    vue: ^3.5.21

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
