packages: []
catalogs:
  build:
    '@iconify-json/carbon': ^1.2.13
    '@vitejs/plugin-vue': ^6.0.1
    jsdom: ^27.0.0
    unocss: ^66.5.1
    unplugin: ^2.3.10
    unplugin-auto-import: ^20.1.0
    unplugin-vue-components: ^29.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.15.0
    vite: ^6.3.6
  dev:
    '@antfu/eslint-config': ^5.3.0
    '@types/node': ^22.18.4
    '@unocss/eslint-plugin': ^66.5.1
    '@vue-macros/volar': ^3.0.0-beta.23
    '@vue/test-utils': ^2.4.6
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
    taze: ^19.6.0
    typescript: ^5.9.2
    vitest: ^3.2.4
    vue-tsc: ^3.0.7
  frontend:
    '@vueuse/core': ^13.9.0
    vue: ^3.5.21
    vue-router: ^4.5.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
